version: '3'

services:
  prac8:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - prac8