# Generated by Django 5.0 on 2023-12-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_value', models.CharField(max_length=200, verbose_name='Хэш')),
                ('diagram_type', models.CharField(max_length=200, verbose_name='Тип')),
                ('image', models.BinaryField(verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Диаграмма',
                'verbose_name_plural': 'Диаграммы',
            },
        ),
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('filename', models.CharField(max_length=255)),
                ('filesize', models.IntegerField()),
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
            ],
        ),
    ]
