# Generated by Django 5.0 on 2023-12-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prac12', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedata',
            name='fileExt',
            field=models.CharField(default='asd', max_length=10),
            preserve_default=False,
        ),
    ]
