version: '3'

services:
  db:
    build:
      dockerfile: dbDockerfile
    environment:
      - MYSQL_DATABASE=table1
      - MYSQL_ROOT_PASSWORD=777
    volumes:
      - db_data:/var/lib/mysql

  web_server:
    build: .
    ports:
      - 80:80
    restart: always
    links:
      - db

volumes:
  db_data: