services:
  db:
    image: 'postgres:15.2'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=user'
      - 'POSTGRES_DB=database'
      - 'POSTGRES_PASSWORD=password'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: "redis:latest"

  auth:
    build: ./auth
    ports:
      - '81:81'
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/database
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_REDIS_HOST: redis

  app:
    build: ./app
    ports:
      - '80:80'
    depends_on:
      - auth
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/database
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

volumes:
  postgres-data: