FROM python:3.11-rc-slim-bullseye
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /code
RUN python -m venv venv
ENV PATH="/code/venv/bin:$PATH"
COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY ./project/ /code/
CMD python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:80